version: '3.1'
services:
  db:
    image: postgres:14.6
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5454:5432
    # create a volumes to persist data 
    volumes:
      - pg_data:/var/lib/postgres/data
  app:
    build: .
    container_name: smart-food
    restart: always
    command: node src/main/app.js
    ports:
      - 8084:8084
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    depends_on:
      - db
volumes:
  pg_data: