version: '3.1'
services:
  db:
    image: postgres:14.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smart-food
    ports:
      - 5454:5432
    # create a volumes to persist data 
    volumes:
      - pg_data:/var/lib/postgres/data
  app:
    build: .
    container_name: smart-food
    restart: always
    command: node src/main/app.js
    ports:
      - 8084:8084
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=smart-food
      - PORT=8084
    depends_on:
      - db
volumes:
  pg_data: